export const quesitons = [
    {
        id: 1,
        quesiton: "Türkiye'nin başkenti neresidir?",
        options: ['İstanbul', 'Ankara', 'İzmir', 'Antalya'],
        answer: 'Ankara',
    },
    {
        id: 2,
        quesiton: "Sözlük tanımına göre hangisi bir sesin adı değildir?",
        options: ['Gümbürtü', 'Hüngürtü', 'Höpürtü', 'Püskürtü'],
        answer: 'Püskürtü',
    },
    {
        id: 3,
        quesiton: "Hasbihal, ne demektir?",
        options: ['Gürültü', 'Geçmiş', 'Sohbet', 'Özlem'],
        answer: 'Sohbet',
    },
    {
        id: 4,
        quesiton: "Ryan Gosling ve Michelle Williams'ın başrolde yer aldığı, 2010'da vizyona giren romantik filmin adı hangisidir?",
        options: ['Silver Linings Playbook', 'La La Land', 'Shutter Island', 'Blue Valentine'],
        answer: 'Blue Valentine',
    },
    {
        id: 5,
        quesiton: "Yağı alınmış süt veya yoğurdun kaynatılmasıyla elde edilen, 'çökelek' adıyla da bilinen peynirin diğer adı nedir?",
        options: ['Acımık', 'Tatlımık', 'Ekşimik', 'Tuzlumuk'],
        answer: 'Ekşimik',
    },
    {
        id: 6,
        quesiton: "'Azı dişi' hangisinin eş anlamlısıdır?",
        options: ['Sindirici diş', 'Öğütücü diş', 'Koparıcı diş', 'Kesici diş'],
        answer: 'Öğütücü diş',
    },
    {
        id: 7,
        quesiton: "Hangi ünlü yapıyı görmek isteyen birinin gitmesi gereken ülke Mısır'dır?",
        options: ['Angkor Vat', 'Keops Piramidi', 'Tac Mahal', 'Pisa Kulesi'],
        answer: 'Keops Piramidi',
    },
    {
        id: 8,
        quesiton: "Osmanlılarda, genel olarak Tanzimat Dönemi'nden Meşrutiyet Dönemi'ne kadar kullanılmış olan 'istanbulin' nedir?",
        options: ['Bir tür kadın şapkası', 'Bir tür erkek ceketi', 'Bir tür nefesli çalgı', 'Bir tür ateşli silah'],
        answer: 'Bir tür erkek ceketi',
    },
    {
        id: 9,
        quesiton: "İnternetteki alışveriş sitelerinde, müşterilerin anlık olarak 'sipariş takibi' yapmasına olanak sağlayan genellikle hangi adda bir sayfa bulunur?",
        options: ['Siparişimin hali hatrı nasıl?', 'Siparşimin canı mı sıkıldı?', 'Siparişim gelmek istemiyor mu?', 'Siparişim nerede?'],
        answer: 'Siparişim nerede?',
    },
    {
        id: 10,
        quesiton: "'Bonjur' hangi anlamda kullanılan bir sözdür?",
        options: ['Günaydın, merhaba', 'Güle güle, görüşürüz', 'Kendine iyi bak, hoşçakal', 'İyi uykular, tatlı rüyalar'],
        answer: 'Günaydın, merhaba',
    },
    {
        id: 11,
        quesiton: "'Elzem' ne demektir?",
        options: ['Çok gerekli, vazgeçilmez', 'Lüzumsuz, gereksiz', 'Enzim salgılayan yapı', 'Burun akıntısı'],
        answer: 'Çok gerekli, vazgeçilmez',
    },
    {
        id: 12,
        quesiton: "Hangi meyvenin 'Valensiya' adıyla satılan bir çeşidi vardır?",
        options: ['Karpuz', 'Şeftali', 'Kivi', 'Portakal'],
        answer: 'Portakal',
    },
    {
        id: 13,
        quesiton: "Hangi iki Osmanlı padişahı kardeş değildir?",
        options: [' II. Mustafa ve III. Ahmed', 'III. Selim ve II. Mahmud', 'Abdülmecid ve Abdülaziz', 'V. Mehmed ve V. Murad'],
        answer: 'III. Selim ve II. Mahmud',
    },
    {
        id: 14,
        quesiton: "Okullarda yoklama yapılırken adı söylenen öğrenci genellikle hangisini yapar?",
        options: ['"Burada!" diye bağırır', '"Neden ben?" diye sorar', '"Buyrun benim" der', '"Yoldayım" diye mesaj atar'],
        answer: '"Burada!" diye bağırır',
    },
    {
        id: 15,
        quesiton: "4 yanlışın 1 doğruyu götürdüğü 100 soruluk çoktan seçmeli bir sınavda 9 boşu ve 8 yanlışı olan birinin neti kaçtır?",
        options: ['83', '81', '79', '77'],
        answer: '81',
    },
]
